name: conditional workflow

on: 
  workflow_dispatch:
  push:
      branches:
        - main 
        - master

env:
  GLOBAL: true

jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      # result: ${{steps.<id>.outputs.<actual-var>}}
      jobresult: ${{steps.setoutput.outputs.result}}
    steps:
      - id: setoutput
        run: echo "result=success" >> $GITHUB_OUTPUT
  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - name: check output var value
      # run: ${{needs.<jobname>.outputs.<namevariable>}}
        run: echo ${{needs.first.outputs.jobresult}}