name: conditional workflow

on: 
  workflow_dispatch:
  push:
      branches:
        - main 
        - master

env:
  GLOBAL: true

jobs:
  outputvar:
    outputs:
      jobResult: ${{steps.setoutputvar.outputs.result}}
    runs-on: ubuntu-latest
    steps:
      - id: setoutputvar
        run: echo "result=success">> $GITHUB_OUTPUT
      - name: check value
        run: echo "result => ${{steps.setoutputvar.outputs.result}}"
  
  useoutputvar:
    needs: outputvar
    runs-on: ubuntu-latest
    steps:
      - name: utilized output 
        run: echo "actual => ${{needs.outputvar.outputs.jobResult}}"