name: conditional workflow

on: 
  workflow_dispatch:
  push:
      branches:
        - main 
        - master

env:
  GLOBAL: true

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: print name 
        if: env.GLOBAL == 'true'
        run: echo "name"
      - name: second step 
        if: success()
        run: |
          echo "Successful"
          exit 1
      - name: Third step (failure)
        if: failure()
        run: |
          echo "Is failed: ${{ failure() }}"
          echo "Failed previous step"