name: reuseable workflow

on: 
  workflow_call: 
    inputs:
      age:
        description: Select your age?
        default: 18
        required: false
        type: number 
    outputs:
      workflow_output_1:
        description: "The first job output"
        value: ${{ jobs.deploy.outputs.outcome }}
      result:
        description: result of the second job
        value: ${{ jobs.deploy.outputs.secondoutput }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.output1.outputs.job_output1}}
      secondoutput: ${{steps.secondoutput.outputs.result }}
    steps:
      - name: print name
        id: output1
        run: |
          echo "Hello young man ${{ inputs.age }}"
          echo "job_output1=testoutputjob" >> $GITHUB_OUTPUT
      - name: Pass the test
        id: secondoutput
        run: echo "result=passed" >> $GITHUB_OUTPUT